sudo: required
language: node_js
node_js: node

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.15.0 

before_install:
  - docker version

script:
  # spin up cluster
  - docker-compose -p server -f docker-compose.yml up -d --build && sleep 20

  # some quick checks to see if it's working as intended
  - docker exec server_server_1 curl localhost:9000
  - docker-compose -p server logs
  
  # run protractor tests against spun up instance
  - docker run -v $(pwd)/app/tests:/tests --network server_default stoplight/prism conduct /tests/scenarios.json -e host=http://server:9000
