env: NODE_ENV
port: PORT
ip: IP
pluginStateStore: KAPTURE_STATE_STORE
downloadPaths:
  root: KAPTURE_DOWNLOAD_PATH

plugins:
  com_transmissionbt:
    transmissionHost: TRANSMISSION_HOST
    transmissionPort: TRANSMISSION_PORT
    transmissionPass: TRANSMISSION_PASS
    transmissionUser: TRANSMISSION_USER
  com_flexget:
    apiToken: FLEXGET_API_TOKEN
    flexgetCheckFrequency: FLEXGET_CHECK_FREQUENCY
    flexgetHost: FLEXGET_HOST
    flexgetPort: FLEXGET_PORT
    flexgetPass: FLEXGET_PASSWORD
    flexgetUser: FLEXGET_USERNAME
