env: default
port: 9000
ip: 0.0.0.0
pluginStateStore: pluginStateStore
system:
    name: default
userInfo:
    email: null
downloadPaths:
    root: downloads
    movies: movies
    shows: tvshows
    music: music
    photos: photos
    default: downloads
plugins:
  com_transmission_bt:
    enabled: true
  com_flexget:
    enabled: true
    flexgetCheckFrequency: 15 # minutes

