env: default
port: 9000
ip: 0.0.0.0
pluginStateStore: pluginStateStore
system:
    name: kapture
userInfo:
    email: null
downloadPaths:
    root: downloads
    movies: movies
    shows: tvshows
    music: music
    photos: photos
    default: downloads
plugins:
  com_transmissionbt:
    enabled: true
    transmissionHost: localhost
    transmissionPort: 9091
  com_flexget:
    enabled: true
    flexgetCheckFrequency: 15 # minutes

