name: Build & Test
on: [push]
jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt install docker.io docker-compose
      - uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kapturebox/server:${{ github.sha }}
          platforms: [linux/amd64, linux/arm64]



  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - run: docker-compose -p server up -d

      # some quick checks to see if it's working as intended
      - run: while ! docker exec server_server_1 curl localhost:9000; do sleep 2; done;
      - run: docker-compose -p server logs

      # run protractor tests against spun up instance
      # TODO: use newman for this: https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/
      - run: docker run -v $(pwd)/app/tests:/tests --network server_default stoplight/prism:v2.0.5 conduct /tests/scenarios.json -e host=http://server:9000


  tag-latest:
    if: github.ref_name == 'master'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: tag image as latest-arm
        run: |
          docker pull kapturebox/server:${{ github.sha }}
          docker tag kapturebox/server:${{ github.sha }} kapturebox/server:latest
          docker push kapturebox/server:latest
